In [1]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
['cold']


In [47]:
y = houses_imp.pop('SalePrice')
y

0       130500.0
1       220000.0
2       109000.0
3       174000.0
4       138500.0
          ...   
2046    298751.0
2047     82500.0
2048    177000.0
2049    144000.0
2050    189000.0
Name: SalePrice, Length: 2051, dtype: float64

In [48]:
houses_imp['SalePrice'] = y
houses_imp
X = houses_imp.iloc[:,:-1]
y = houses_imp.iloc[:,-1]

In [49]:
y

0       130500.0
1       220000.0
2       109000.0
3       174000.0
4       138500.0
          ...   
2046    298751.0
2047     82500.0
2048    177000.0
2049    144000.0
2050    189000.0
Name: SalePrice, Length: 2051, dtype: float64

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 3)

In [53]:
X_train

Id  MS_SubClass  Lot_Frontage  Lot_Area  Overall_Qual  Overall_Cond  \
1133   115.0         60.0          80.0   10421.0           7.0           5.0   
1253   152.0        190.0          70.0   13587.0           5.0           5.0   
1666  1664.0         20.0           0.0   10530.0           6.0           5.0   
48     132.0         20.0          80.0    9920.0           5.0           5.0   
1487  2053.0         80.0          65.0   14149.0           5.0           8.0   
...      ...          ...           ...       ...           ...           ...   
968    839.0         60.0          43.0   10667.0           7.0           6.0   
952   2231.0         20.0          70.0   18044.0           8.0           5.0   
1667  1433.0         20.0          75.0    9525.0           5.0           6.0   
1688  1525.0         70.0          79.0   11526.0           6.0           7.0   
1898   929.0         20.0          90.0   13339.0           6.0           6.0   

      Year_Built  Year_Remod/Add  Mas_Vnr_Area  BsmtFin_SF_1  BsmtFin_SF_2  \
1133      1988.0          1988.0          42.0         394.0           0.0   
1253      1958.0          1958.0           0.0         532.0           0.0   
1666      1971.0          1971.0           0.0         282.0          35.0   
48        1954.0          1954.0         110.0         354.0         290.0   
1487      1964.0          2001.0          50.0          68.0         722.0   
...          ...             ...           ...           ...           ...   
968       1996.0          1996.0           0.0         385.0         344.0   
952       1986.0          1986.0           0.0           0.0           0.0   
1667      1995.0          2006.0           0.0           0.0           0.0   
1688      1922.0          1994.0           0.0           0.0           0.0   
1898      1960.0          1960.0         132.0          65.0         875.0   

      Bsmt_Unf_SF  Total_Bsmt_SF  1st_Flr_SF  2nd_Flr_SF  Low_Qual_Fin_SF  \
1133        586.0          980.0       980.0       734.0              0.0   
1253        456.0          988.0       988.0         0.0              0.0   
1666        664.0          981.0       981.0         0.0              0.0   
48          412.0         1056.0      1063.0         0.0              0.0   
1487        190.0          980.0      1020.0         0.0              0.0   
...           ...            ...         ...         ...              ...   
968          70.0          799.0       827.0       834.0              0.0   
952         279.0          279.0      2726.0         0.0              0.0   
1667       1099.0         1099.0      1099.0         0.0              0.0   
1688        588.0          588.0      1423.0       748.0            384.0   
1898        621.0         1561.0      1561.0         0.0              0.0   

      Gr_Liv_Area  Bsmt_Full_Bath  Bsmt_Half_Bath  Full_Bath  Half_Bath  \
1133       1714.0             0.0             0.0        2.0        1.0   
1253        988.0             1.0             0.0        1.0        0.0   
1666        981.0             1.0             0.0        1.0        1.0   
48         1063.0             1.0             0.0        1.0        0.0   
1487       1020.0             0.0             1.0        2.0        0.0   
...           ...             ...             ...        ...        ...   
968        1661.0             1.0             0.0        2.0        1.0   
952        2726.0             0.0             0.0        2.0        1.0   
1667       1099.0             0.0             0.0        1.0        1.0   
1688       2555.0             0.0             0.0        2.0        0.0   
1898       1561.0             1.0             0.0        2.0        0.0   

      Bedroom_AbvGr  Kitchen_AbvGr  TotRms_AbvGrd  Fireplaces  Garage_Yr_Blt  \
1133            3.0            1.0            7.0         1.0         1988.0   
1253            2.0            1.0            5.0         0.0         1958.0   
1666            3.0            1.0